version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore: '
    labels:
      - 'dependencies'